name: Build and Deploy to Azure VM

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Copy files to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          port: ${{ secrets.VM_PORT || 22 }}
          source: "dist/"  # Asume que el build va a dist/
          target: "/var/www/form-app"
          rm: true  # Borra archivos antiguos

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          port: ${{ secrets.VM_PORT || 22 }}
          script: |
            cd /var/www/form-app
            npm ci --production
            # Reinicia PM2 o el servicio
            if pm2 describe app >/dev/null 2>&1; then
              pm2 reload app --update-env
            else
              pm2 start server.js --name app
            fi
            pm2 save